apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-api-canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-api
  template:
    metadata:
      name: api
      labels:
        app: simple-api
        role: api
        env: canary
       
    spec:
      containers:
      - name: api
        image: saturn203/simple-api:v1.0.0
        resources:
          limits:
            memory: "500Mi"
            cpu: "100m"
        imagePullPolicy: Always
        ports:
        - name: api
          containerPort: 9001
 



