apiVersion: v1
kind: Service
apiVersion: v1
metadata:
  name: simple-api-svc
spec:
  selector:
    role: api
    app: simple-api
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 9001
    
  type: LoadBalancer